### ISSUE TITLE
ref(f2)1: Game List UI Redesign

### ISSUE THREAD

**Issue by ChelleAmon** [mean-stack-apprentices/problox#128]
-Re-design UI interface for the users-games-list page

**Comment by ChelleAmon** [comment]
I need some help styling out the user games list page.

**Comment by Aman-codde** [comment]
merch-details page styling is working, I have an idea if I shift the merch-details stying to global styling then it could work for both

**Comment by ChelleAmon** [comment]
Closing this issue but will reopen it later once a global css is implemented

**Comment by ChelleAmon** [comment]
Reopen issue. Assign to Chazz

**Comment by czcarrizales** [comment]
I'll start working on it today. Thank ya, thank ya.
